name: flutter_entity
description: "Entity: Represents a structured data object. Response: Communicates operation outcomes with data and status indicators."
version: 1.0.0
repository: https://github.com/Mohiuddin655-PUB/flutter_entity.git

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
